Repository GaloisInc/VERSE-OpenSUT, pull requests merged in 2025-03, with the labels that each got.

#157 Fix interleaving when running multiple OpenSUT guests
  Dockerfile
  docs/OPENSUT_DOCKER.md
  src/pkvm_setup/vm_scripts/setup_common_guest.sh
  src/vm_runner/src/config.rs
  src/vm_runner/src/lib.rs
  src/vm_runner/tests/opensut-dev/base_nested.toml
  src/vm_runner/tests/opensut-dev/base_single.toml
  src/vm_runner/tests/opensut-dev/host.toml
  src/vm_runner/tests/opensut-dev/logging_config.sh
Labels: hardware, SoW TA2.1.1.A

#159 Change Request 2: MPS communicates over socket
  .github/workflows/main.yml
  components/include/cn_array_utils.h
  components/include/cn_memory.h
  components/include/cn_sys.h
  components/mission_protection_system/src/include/common.h
  components/mission_protection_system/src/posix_main.c
  components/mission_protection_system/tests/run_all.py
  components/mission_protection_system/tests/runner.py
  components/platform_crypto/shave_trusted_boot/trusted_boot.c
Labels: application software, change request

#170 opensut_boot: check expected hash
  src/vm_runner/.gitignore
  src/vm_runner/README.md
  src/vm_runner/opensut-boot.service
  src/vm_runner/opensut-trusted-boot.service
  src/vm_runner/src/lib.rs
  src/vm_runner/tests/opensut-dev/base_nested.toml.in
  src/vm_runner/tests/opensut-dev/build_img.sh
  src/vm_runner/tests/opensut-dev/host.toml.in
Labels: application software, SoW TA2.1.1.A

#172 Gus/issue107
  components/include/cn_array_utils.h
  components/include/cn_memory.h
  components/include/cn_strings.h
  components/include/cn_sys.h
  components/mission_key_management/client.c
  components/mission_key_management/client.h
  components/mission_protection_system/src/common.c
  components/mission_protection_system/src/components/actuation_unit.c
  components/mission_protection_system/src/components/instrumentation.c
  components/mission_protection_system/src/core.c
  components/mission_protection_system/src/include/actuate.h
  components/mission_protection_system/src/include/actuation_logic.h
  components/mission_protection_system/src/include/common.h
  components/mission_protection_system/src/include/core.h
  components/mission_protection_system/src/include/instrumentation.h
  components/mission_protection_system/src/include/platform.h
  components/mission_protection_system/src/include/sense_actuate.h
  components/mission_protection_system/src/posix_main.c
  components/platform_crypto/shave_trusted_boot/firmware.c
  components/platform_crypto/shave_trusted_boot/hmac_sha256.h
  components/platform_crypto/shave_trusted_boot/sha_256.h
  components/platform_crypto/shave_trusted_boot/trusted_boot.c
  components/platform_crypto/shave_trusted_boot/xmss-library/include/signing.h
  components/platform_crypto/shave_trusted_boot/xmss-library/include/verification.h
Labels: documentation

#173 ci: tag docker image based on branch/tag being built
  .github/workflows/main.yml
Labels: infrastructure, SoW TA2.1.1.A
